import { Product } from "@/components/pages/umrah/product";

export const productsData = [
    {
      id: 1,
      category: "umrah",
      src: "/product/product.jpg",
      title: "Paket Umrah Jakarta Jeddah 9 Hari",
      price: "23.500.000",
      rating: 5,
      sold: 100,
      time: "9 Hari",
      airline: "Lion Air",
      hotel: "Bintang 5",
    },
  ];

export const allProductsData: Product[] = [
  {
    id: 1,
    category: "Awal Musim",
    src: "/product/product.jpg",
    title: "Paket Umrah Super Hemat Awal Musim",
    price: "25000000",
    rating: 4.8,
    sold: 150,
    time: "9 Hari",
    airline: "Saudi Airlines",
    hotel: "Bintang 4",
  },
  {
    id: 2,
    category: "Ramadhan",
    src: "/product/product.jpg",
    title: "Paket Umrah Spesial Ramadhan",
    price: "45000000",
    rating: 5.0,
    sold: 95,
    time: "15 Hari",
    airline: "Garuda Indonesia",
    hotel: "Bintang 5",
  },
  {
    id: 3,
    category: "Liburan",
    src: "/product/product.jpg",
    title: "Umrah Plus Turki Liburan Sekolah",
    price: "35000000",
    rating: 4.9,
    sold: 210,
    time: "12 Hari",
    airline: "Turkish Airlines",
    hotel: "Bintang 5",
  },
  {
    id: 4,
    category: "Promo",
    src: "/product/product.jpg",
    title: "Promo Terbatas Umrah Berkah",
    price: "22500000",
    rating: 4.7,
    sold: 300,
    time: "9 Hari",
    airline: "Lion Air",
    hotel: "Bintang 3",
  },
  {
    id: 5,
    category: "Umrah Plus",
    src: "/product/product.jpg",
    title: "Umrah Plus Kairo & Alexandria",
    price: "38000000",
    rating: 4.9,
    sold: 80,
    time: "14 Hari",
    airline: "EgyptAir",
    hotel: "Bintang 5",
  },
  {
    id: 6,
    category: "Agent",
    src: "/product/product.jpg",
    title: "Paket Khusus Agen Perjalanan",
    price: "24000000",
    rating: 4.8,
    sold: 120,
    time: "10 Hari",
    airline: "Saudi Airlines",
    hotel: "Bintang 4",
  },
  {
    id: 7,
    category: "Awal Musim",
    src: "/product/product.jpg",
    title: "Paket Umrah Ekonomis Awal Musim",
    price: "23000000",
    rating: 4.6,
    sold: 180,
    time: "9 Hari",
    airline: "Citilink",
    hotel: "Bintang 3",
  },
  {
    id: 8,
    category: "Ramadhan",
    src: "/product/product.jpg",
    title: "Paket I'tikaf Lailatul Qadar",
    price: "55000000",
    rating: 5.0,
    sold: 50,
    time: "10 Hari Terakhir",
    airline: "Garuda Indonesia",
    hotel: "Bintang 5 Dekat Masjidil Haram",
  },
  {
    id: 9,
    category: "Liburan",
    src: "/product/product.jpg",
    title: "Umrah Keluarga Ceria Libur Lebaran",
    price: "36000000",
    rating: 4.8,
    sold: 150,
    time: "10 Hari",
    airline: "Saudi Airlines",
    hotel: "Bintang 4 Suite Keluarga",
  },
  {
    id: 10,
    category: "Promo",
    src: "/product/product.jpg",
    title: "Flash Sale Umrah Akhir Tahun",
    price: "21000000",
    rating: 4.5,
    sold: 450,
    time: "9 Hari",
    airline: "Lion Air",
    hotel: "Bintang 3",
  },
  {
    id: 11,
    category: "Umrah Plus",
    src: "/product/product.jpg",
    title: "Umrah Plus Dubai City Tour",
    price: "39500000",
    rating: 4.9,
    sold: 110,
    time: "12 Hari",
    airline: "Emirates",
    hotel: "Bintang 5",
  },
  {
    id: 12,
    category: "Awal Musim",
    src: "/product/product.jpg",
    title: "Paket Umrah Regular Awal Musim",
    price: "26500000",
    rating: 4.7,
    sold: 200,
    time: "9 Hari",
    airline: "Garuda Indonesia",
    hotel: "Bintang 4",
  },
  {
    id: 13,
    category: "Ramadhan",
    src: "/product/product.jpg",
    title: "Umrah Awal Ramadhan Penuh Berkah",
    price: "40000000",
    rating: 4.9,
    sold: 130,
    time: "12 Hari",
    airline: "Saudi Airlines",
    hotel: "Bintang 5",
  },
  {
    id: 14,
    category: "Liburan",
    src: "/product/product.jpg",
    title: "Liburan Akhir Tahun Umrah Plus Aqsa",
    price: "42000000",
    rating: 5.0,
    sold: 90,
    time: "14 Hari",
    airline: "Qatar Airways",
    hotel: "Bintang 5",
  },
  {
    id: 15,
    category: "Promo",
    src: "/product/product.jpg",
    title: "Promo Umrah Group Keberangkatan",
    price: "22000000",
    rating: 4.6,
    sold: 250,
    time: "9 Hari",
    airline: "Citilink",
    hotel: "Bintang 3",
  },
  {
    id: 16,
    category: "Agent",
    src: "/product/product.jpg",
    title: "Paket Group Eksklusif untuk Agen",
    price: "23500000",
    rating: 4.7,
    sold: 80,
    time: "10 Hari",
    airline: "Garuda Indonesia",
    hotel: "Bintang 4",
  },
  {
    id: 17,
    category: "Umrah Plus",
    src: "/product/product.jpg",
    title: "Jelajah Sejarah Islam: Umrah Plus Spanyol",
    price: "48000000",
    rating: 4.9,
    sold: 65,
    time: "15 Hari",
    airline: "Turkish Airlines",
    hotel: "Bintang 4 & 5",
  },
  {
    id: 18,
    category: "Awal Musim",
    src: "/product/product.jpg",
    title: "Keberangkatan November Hemat",
    price: "24500000",
    rating: 4.7,
    sold: 160,
    time: "9 Hari",
    airline: "Saudi Airlines",
    hotel: "Bintang 4",
  },
  {
    id: 19,
    category: "Ramadhan",
    src: "/product/product.jpg",
    title: "Full Ramadhan di Tanah Suci",
    price: "65000000",
    rating: 5.0,
    sold: 30,
    time: "30 Hari",
    airline: "Garuda Indonesia",
    hotel: "Bintang 5",
  },
  {
    id: 20,
    category: "Liburan",
    src: "/product/product.jpg",
    title: "Paket Umrah Libur Natal & Tahun Baru",
    price: "37000000",
    rating: 4.8,
    sold: 190,
    time: "11 Hari",
    airline: "Emirates",
    hotel: "Bintang 5",
  },
  {
    id: 21,
    category: "Promo",
    src: "/product/product.jpg",
    title: "Promo Awal Tahun Penuh Semangat",
    price: "23000000",
    rating: 4.6,
    sold: 220,
    time: "9 Hari",
    airline: "Lion Air",
    hotel: "Bintang 4",
  },
  {
    id: 22,
    category: "Awal Musim",
    src: "/product/product.jpg",
    title: "Umrah VIP Awal Musim",
    price: "30000000",
    rating: 4.9,
    sold: 100,
    time: "9 Hari",
    airline: "Garuda Indonesia",
    hotel: "Bintang 5",
  },
  {
    id: 23,
    category: "Agent",
    src: "/product/product.jpg",
    title: "Komisi Terbaik Paket Agen",
    price: "22800000",
    rating: 4.7,
    sold: 140,
    time: "9 Hari",
    airline: "Saudi Airlines",
    hotel: "Bintang 4",
  },
  {
    id: 24,
    category: "Umrah Plus",
    src: "/product/product.jpg",
    title: "Umrah Plus Thaif & City Tour Jeddah",
    price: "29000000",
    rating: 4.8,
    sold: 130,
    time: "10 Hari",
    airline: "Saudi Airlines",
    hotel: "Bintang 4",
  },
  {
    id: 25,
    category: "Ramadhan",
    src: "/product/product.jpg",
    title: "Umrah Malam Ganjil Ramadhan",
    price: "50000000",
    rating: 5.0,
    sold: 70,
    time: "13 Hari",
    airline: "Garuda Indonesia",
    hotel: "Bintang 5",
  },
  {
    id: 26,
    category: "Liburan",
    src: "/product/product.jpg",
    title: "Paket Umrah Liburan Imlek",
    price: "33000000",
    rating: 4.7,
    sold: 115,
    time: "10 Hari",
    airline: "Qatar Airways",
    hotel: "Bintang 4",
  },
  {
    id: 27,
    category: "Promo",
    src: "/product/product.jpg",
    title: "Promo Spesial Maulid Nabi",
    price: "24000000",
    rating: 4.8,
    sold: 280,
    time: "9 Hari",
    airline: "Lion Air",
    hotel: "Bintang 4",
  },
  {
    id: 28,
    category: "Awal Musim",
    src: "/product/product.jpg",
    title: "Umrah Oktober Ceria",
    price: "25500000",
    rating: 4.7,
    sold: 175,
    time: "9 Hari",
    airline: "Saudi Airlines",
    hotel: "Bintang 4",
  },
  {
    id: 29,
    category: "Umrah Plus",
    src: "/product/product.jpg",
    title: "Umrah Plus Wisata Halal Uzbekistan",
    price: "46000000",
    rating: 4.9,
    sold: 55,
    time: "14 Hari",
    airline: "Uzbekistan Airways",
    hotel: "Bintang 4 & 5",
  },
  {
    id: 30,
    category: "Agent",
    src: "/product/product.jpg",
    title: "Paket Insentif Agen Terbaik",
    price: "23200000",
    rating: 4.8,
    sold: 95,
    time: "10 Hari",
    airline: "Garuda Indonesia",
    hotel: "Bintang 4",
  },
  {
    id: 31,
    category: "Ramadhan",
    src: "/product/product.jpg",
    title: "Paket Umrah Tengah Ramadhan",
    price: "42500000",
    rating: 4.9,
    sold: 110,
    time: "12 Hari",
    airline: "Saudi Airlines",
    hotel: "Bintang 5",
  },
  {
    id: 32,
    category: "Liburan",
    src: "/product/product.jpg",
    title: "Umrah Plus Yordania Petra",
    price: "41000000",
    rating: 4.9,
    sold: 85,
    time: "13 Hari",
    airline: "Royal Jordanian",
    hotel: "Bintang 5",
  },
  {
    id: 33,
    category: "Promo",
    src: "/product/product.jpg",
    title: "Promo Hari Pahlawan",
    price: "22800000",
    rating: 4.7,
    sold: 320,
    time: "9 Hari",
    airline: "Lion Air",
    hotel: "Bintang 3",
  },
  {
    id: 34,
    category: "Awal Musim",
    src: "/product/product.jpg",
    title: "Umrah Desember Awal",
    price: "27000000",
    rating: 4.8,
    sold: 140,
    time: "10 Hari",
    airline: "Garuda Indonesia",
    hotel: "Bintang 4",
  },
  {
    id: 35,
    category: "Umrah Plus",
    src: "/product/product.jpg",
    title: "Umrah Plus Ziarah Tiga Masjid Suci",
    price: "43000000",
    rating: 5.0,
    sold: 100,
    time: "14 Hari",
    airline: "Saudi Airlines",
    hotel: "Bintang 5",
  },
  {
    id: 36,
    category: "Liburan",
    src: "/product/product.jpg",
    title: "Paket Umrah Private Keluarga",
    price: "39000000",
    rating: 5.0,
    sold: 60,
    time: "9 Hari",
    airline: "Garuda Indonesia",
    hotel: "Bintang 5 Suite",
  },
  {
    id: 37,
    category: "Promo",
    src: "/product/product.jpg",
    title: "Promo Gajian, Berangkat Umrah",
    price: "23500000",
    rating: 4.6,
    sold: 260,
    time: "9 Hari",
    airline: "Citilink",
    hotel: "Bintang 4",
  },
  {
    id: 38,
    category: "Ramadhan",
    src: "/product/product.jpg",
    title: "Umrah Syawal Setelah Ramadhan",
    price: "30000000",
    rating: 4.8,
    sold: 150,
    time: "10 Hari",
    airline: "Saudi Airlines",
    hotel: "Bintang 5",
  },
  {
    id: 39,
    category: "Agent",
    src: "/product/product.jpg",
    title: "Paket Landing Arrangement Agen",
    price: "15000000",
    rating: 4.9,
    sold: 200,
    time: "7 Hari",
    airline: "Tanpa Tiket",
    hotel: "Bintang 4",
  },
  {
    id: 40,
    category: "Awal Musim",
    src: "/product/product.jpg",
    title: "Paket Umrah Mabrur Awal Musim",
    price: "26000000",
    rating: 4.8,
    sold: 190,
    time: "9 Hari",
    airline: "Garuda Indonesia",
    hotel: "Bintang 4",
  },
];


export const productsData_12: Product[] = allProductsData.slice(0, 12);

export const programUmrahProducts: Product[] = [
  {
    id: 1,
    category: "Awal Musim",
    src: "/product/product.jpg",
    title: "Paket Umrah Super Hemat Awal Musim",
    price: "25.000.000",
    rating: 4.8,
    sold: 150,
    time: "9 Hari",
    airline: "Saudi Airlines",
    hotel: "Bintang 4",
  },
  {
    id: 2,
    category: "Ramadhan",
    src: "/product/product.jpg",
    title: "Paket Umrah Spesial Ramadhan",
    price: "45.000.000",
    rating: 5.0,
    sold: 95,
    time: "15 Hari",
    airline: "Garuda Indonesia",
    hotel: "Bintang 5",
  },
  {
    id: 3,
    category: "Liburan",
    src: "/product/product.jpg",
    title: "Umrah Plus Turki Liburan Sekolah",
    price: "35.000.000",
    rating: 4.9,
    sold: 210,
    time: "12 Hari",
    airline: "Turkish Airlines",
    hotel: "Bintang 5",
  },
  {
    id: 4,
    category: "Promo",
    src: "/product/product.jpg",
    title: "Promo Terbatas Umrah Berkah",
    price: "22.500.000",
    rating: 4.7,
    sold: 300,
    time: "9 Hari",
    airline: "Lion Air",
    hotel: "Bintang 3",
  },
  {
    id: 5,
    category: "Umrah Plus",
    src: "/product/product.jpg",
    title: "Umrah Plus Kairo & Alexandria",
    price: "38.000.000",
    rating: 4.9,
    sold: 80,
    time: "14 Hari",
    airline: "EgyptAir",
    hotel: "Bintang 5",
  },
  {
    id: 6,
    category: "Agent",
    src: "/product/product.jpg",
    title: "Paket Khusus Agen Perjalanan",
    price: "24.000.000",
    rating: 4.8,
    sold: 120,
    time: "10 Hari",
    airline: "Saudi Airlines",
    hotel: "Bintang 4",
  },
    {
    id: 7,
    category: "Awal Musim",
    src: "/product/product.jpg",
    title: "Paket Umrah Ekonomis Awal Musim",
    price: "23.000.000",
    rating: 4.6,
    sold: 180,
    time: "9 Hari",
    airline: "Citilink",
    hotel: "Bintang 3",
  },
  {
    id: 8,
    category: "Ramadhan",
    src: "/product/product.jpg",
    title: "Paket I'tikaf Lailatul Qadar",
    price: "55.000.000",
    rating: 5.0,
    sold: 50,
    time: "10 Hari Akhir Ramadhan",
    airline: "Garuda Indonesia",
    hotel: "Bintang 5 Dekat Masjidil Haram",
  },
  {
    id: 9,
    category: "Liburan",
    src: "/product/product.jpg",
    title: "Umrah Keluarga Ceria Libur Lebaran",
    price: "36.000.000",
    rating: 4.8,
    sold: 150,
    time: "10 Hari",
    airline: "Saudi Airlines",
    hotel: "Bintang 4 Suite Keluarga",
  },
];